export class PlanillaSuicidio {
  codigoDpto?: number;
  codigoUnidad?: number;
  codigoLocalidad?: number;
  nroPreventivo?: number;
  fechaHecho?: string;
  horaHecho?: string;
  viaPublica?: boolean;
  domParticular?: boolean;
  viaTren?: boolean;
  carcelComisaria?: boolean;
  otroLugar?: boolean;
  otroLugarEsp?: string;
  sinDeterminarLugar?: boolean;
  armaFuego?: boolean;
  armaElementoContundente?: boolean;
  sumersion?: boolean;
  envenenamiento?: boolean;
  ahorcamiento?: boolean;
  seArroja?: boolean;
  seArrojaVia?: boolean;
  //agregue nuevo
  seIncinera?: boolean;
  //</agregue nuevo>
  otraModalidad?: boolean;
  sinDeterminarModalidad?: boolean;
  especificarModalidad?: string;
  intervencionPolicial?: boolean;
  nroDocumentoSuicida?: number;
  nombreSuicida?: string;
  apellidoSuicida?: string;
  codigoSexo?: number;
  edadVictima?: number;
  generoVictima?: number;
  especifGeneroVict?: string;
}
